name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main  # Esto se ejecutará cuando se haga un push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configurar región predeterminada de Google Cloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      - name: Configurar Docker para Google Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev


#      - name: Crear repositorio en Artifact Registry (si no existe)
#        run: |
#          gcloud artifacts repositories create my-docker-repo \
#            --repository-format=docker \
#            --location=us-central1 \
#            --description="Repositorio Docker para la aplicación"

#      - name: Listar servicios en Cloud Run
#        run: |
#          gcloud run services list --platform managed --region us-central1


      - name: Construir y subir imagen Docker a Artifact Registry
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo-final/ci-cd-recommender-app-uhem:latest .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo-final/ci-cd-recommender-app-uhem:latest

      - name: Desplegar en Cloud Run
        run: |
          gcloud run deploy ci-cd-recommender-app-uhem --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo-final/ci-cd-recommender-app-uhem:latest --platform managed --allow-unauthenticated --region us-central1